#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/katedoxey/.pyenv/versions/3.8.3/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/katedoxey/.pyenv/versions/3.8.3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/katedoxey/Desktop/research/projects/tinnitus model/code/mod/x86_64/.libs/libnrnmech.so" "$@"
